<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
        <relativePath/>
    </parent>
    <groupId>com.storage</groupId>
    <artifactId>engine</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>engine</name>
    <description>Storage Engine Service</description>
    <properties>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>cn.edu.tsinghua</groupId>
            <artifactId>iginx-session</artifactId>
            <version>0.7.2</version>
        </dependency>
        <dependency>
            <groupId>cn.edu.tsinghua</groupId>
            <artifactId>iginx-thrift</artifactId>
            <version>0.7.2</version>
        </dependency>
        <dependency>
            <groupId>cn.edu.tsinghua</groupId>
            <artifactId>iginx-shared</artifactId>
            <version>0.7.2</version>
        </dependency>
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>4.4.16</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>iginx</id>
            <name>IGinX GitHub repository</name>
            <url>https://iginx-thu.github.io/IGinX/maven-repo</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
