server.port=8080
spring.application.name=storage-engine

iginx.host=127.0.0.1
iginx.port=6888
iginx.username=root
iginx.password=root

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# IGinX node hot-add defaults
deploy.iginx.script-path=/home/ubuntu/ScaleStore/backend/scripts/deploy_iginx.sh
deploy.iginx.default-package-path=/home/ubuntu/ScaleStore/backend/packages/IGinX-FastDeploy-0.8.0.tar.gz
deploy.iginx.default-zk-connection=127.0.0.1:2181
deploy.iginx.default-directory=~
